name: Build APK for Flutter

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Flutter
      uses: subosito/flutter-action@v2  
      with:
        flutter-version: '3.0.0'  

    - name: Install dependencies
      run: flutter pub get  

    - name: Build APK
      run: flutter build apk --release 

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4  
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk  
